### ISSUE TITLE
UIpdate User 

### ISSUE THREAD

**Issue by Mubeen1322** [cupidknot/Android-App-Assessment-01#3]
Hello sir,

This is Mubeen thank you so much for giving me an opportunity for practical round.

I have checked it in postman its giving error( Integrity constraint violation: 1048 Column ') and in updateuser there are extra parameters (religion, updated , updated_on) .

**Comment by satputekuldip** [comment]
share full Error

**Comment by Mubeen1322** [comment]
when i checked next its done so .Update Done.

**Comment by Mubeen1322** [comment]
Thank you so much for reply its done when i tried for next time its giving
correct response in postman.
